disabled_rules: # rule identifiers to exclude from running
  - line_length
  - force_cast
  - force_try
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - vendor
