notifications:
  email: false
language: swift
osx_image: xcode9.2
xcode_workspace: ThaiTechEventsCalendar.xcworkspace
xcode_scheme: ThaiTechEventsCalendarTests
before_install:
  - bundle install
  - pod repo update
script:
  - xcodebuild test -workspace ThaiTechEventsCalendar.xcworkspace -scheme ThaiTechEventsCalendarTests CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -destination 'platform=iOS Simulator,name=iPhone 7'
after_success:
  - bash <(curl -s https://codecov.io/bash)
